EXPERIMENT:
  NAME: ""
  TAG: "edkd,res56,shuv1"
  PROJECT: "dkd_teachers_shuv1"
DISTILLER:
  TYPE: "EDKD"
  TEACHER: "resnet56"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

